sudo: false
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
language: groovy
env:
  global:
  - TERM=dumb
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: ./gradlew clean check --info --refresh-dependencies
after_failure: ./travis/junit-errors-to-stdout.sh
