sudo: false
cache:
  directories:
  - $HOME/.gradle/wrapper
language: groovy
env:
  global:
  - TERM=dumb
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: ./gradlew check --info --refresh-dependencies -Dgrails.env=test
after_failure: ./travis/junit-errors-to-stdout.sh
